-- Projeto Flamengo 2019
-- Cadastro dos jogadores

INSERT INTO jogador (id_jogador, nome, posicao, nacionalidade) VALUES
(1, 'Diego Alves', 'Goleiro', 'Brasil'),
(2, 'César', 'Goleiro', 'Brasil'),
(3, 'Gabriel Batista', 'Goleiro', 'Brasil'),
(4, 'Hugo Souza', 'Goleiro', 'Brasil'),
(5, 'Rodinei', 'Lateral', 'Brasil'),
(6, 'Rodrigo Caio', 'Zagueiro', 'Brasil'),
(7, 'Pablo Marí', 'Zagueiro', 'Espanha'),
(8, 'Thuler', 'Zagueiro', 'Brasil'),
(9, 'Rhodolfo', 'Zagueiro', 'Brasil'),
(10, 'Renê', 'Lateral', 'Brasil'),
(11, 'Rafinha', 'Lateral', 'Brasil'),
(12, 'Filipe Luís', 'Lateral', 'Brasil'),
(13, 'Willian Arão', 'Meio-campo', 'Brasil'),
(14, 'Gerson', 'Meio-campo', 'Brasil'),
(15, 'Éverton Ribeiro', 'Meio-campo', 'Brasil'),
(16, 'De Arrascaeta', 'Meio-campo', 'Uruguai'),
(17, 'Diego', 'Meio-campo', 'Brasil'),
(18, 'Piris da Motta', 'Meio-campo', 'Paraguai'),
(19, 'Reinier', 'Meio-campo', 'Brasil'),
(20, 'Vitinho', 'Atacante', 'Brasil'),
(21, 'Bruno Henrique', 'Atacante', 'Brasil'),
(22, 'Gabriel Barbosa', 'Atacante', 'Brasil'),
(23, 'Lincoln', 'Atacante', 'Brasil'),
(24, 'Gustavo Cuéllar', 'Meio-campo', 'Colômbia'),
(25, 'Pará', 'Lateral', 'Brasil'),
(26, 'Miguel Trauco', 'Lateral', 'Peru'),
(27, 'Orlando Berrío', 'Atacante', 'Colômbia'),
(28, 'Fernando Uribe', 'Atacante', 'Colômbia'),
(29, 'Ronaldo', 'Meio-campo', 'Brasil'),
(30, 'Hugo Moura', 'Meio-campo', 'Brasil'),
(31, 'Vitor Gabriel', 'Atacante', 'Brasil'),
(32, 'Bill', 'Atacante', 'Brasil'),
(33, 'Jean Lucas', 'Meio-campo', 'Brasil'),
(34, 'Henrique Dourado', 'Atacante', 'Brasil'),
(35, 'Lucas Silva', 'Atacante', 'Brasil');
